// Mocks generated by Mockito 5.4.2 from annotations
// in harmo_futsal/test/unit_testing/reviews_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:harmo_futsal/core/failure/failure.dart' as _i6;
import 'package:harmo_futsal/features/reviews/domain/entity/reviews_entity.dart'
    as _i7;
import 'package:harmo_futsal/features/reviews/domain/entity/user_id_entity.dart'
    as _i8;
import 'package:harmo_futsal/features/reviews/domain/repository/review_reposit0ry.dart'
    as _i2;
import 'package:harmo_futsal/features/reviews/domain/use_case/review_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIReviewRepository_0 extends _i1.SmartFake
    implements _i2.IReviewRepository {
  _FakeIReviewRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewUseCase extends _i1.Mock implements _i4.ReviewUseCase {
  @override
  _i2.IReviewRepository get reviewRepository => (super.noSuchMethod(
        Invocation.getter(#reviewRepository),
        returnValue: _FakeIReviewRepository_0(
          this,
          Invocation.getter(#reviewRepository),
        ),
        returnValueForMissingStub: _FakeIReviewRepository_0(
          this,
          Invocation.getter(#reviewRepository),
        ),
      ) as _i2.IReviewRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ReviewEntity>>> getAllReviews() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllReviews,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.ReviewEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.ReviewEntity>>(
          this,
          Invocation.method(
            #getAllReviews,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.ReviewEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.ReviewEntity>>(
          this,
          Invocation.method(
            #getAllReviews,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ReviewEntity>>>);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> addReview(String? review) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReview,
          [review],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addReview,
            [review],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addReview,
            [review],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.UserIdEntity>>> getUserById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.UserIdEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.UserIdEntity>>(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.UserIdEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.UserIdEntity>>(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i8.UserIdEntity>>>);
}
